### PR TITLE
Add Launch Blog Post button

### PR DESCRIPTION
**Pull request by wilhelmklopp**
Adds a button for the launch blog post, which previously had nothing pointing to it.

@ChristopherHammond13 @hennersz Pls review, merge, and deploy

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
@xoneco can you please rebase on master and trigger a rebuild? Because of the way that statics are handled we must rebuild after merging in PRs, and each PR that's merged will trigger a conflict with the others.

**Comment by wilhelmklopp** [comment]
@ChristopherHammond13 screw build files

**Comment by wilhelmklopp** [comment]
@ChristopherHammond13 this should be good to go

**Comment by ChristopherHammond13** [comment]
Merged and pulled

**Pull request merged**
